DROP TABLE CART_ITEM IF EXISTS;


CREATE TABLE CART_ITEM (
  ID VARCHAR(75),
  PRODUCT_ID VARCHAR(25) FOREIGN KEY REFERENCES
  PRODUCTS(ID),
  CART_ID varchar(50) FOREIGN KEY REFERENCES
  CART(ID),
  QUANTITY BIGINT,
  CONSTRAINT CART_ITEM_PK PRIMARY KEY (ID,CART_ID)
);

