INSERT INTO CUSTOMERS VALUES (1234, 'Bill', 'Kharkiv', 23);
INSERT INTO CUSTOMERS VALUES (1235, 'Olga', 'Kiev', 47);
INSERT INTO CUSTOMERS VALUES (1369, 'Anya', 'Dnipro', 12);
INSERT INTO CUSTOMERS VALUES (2369, 'Timur', 'Dnipro', 19);


